apiVersion: apps/v1
kind: Deployment
metadata:
  name: messageservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messageservice
  template:
    metadata:
      labels:
        app: messageservice
    spec:
      containers:
      - name: messageservice
        image: messageservice:k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "MessageService"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"